name: Awesome Vue Project

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.15.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
